/**
 * generated by Xtext 2.11.0
 */
package org.mondo.collaboration.policy.ide;

import com.google.inject.Injector;
import org.mondo.collaboration.policy.RulesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RulesIdeSetup extends RulesStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from RulesIdeModule to Module");
  }
}
