/**
 * generated by Xtext 2.10.0
 */
package org.mondo.collaboration.policy.rules;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Asset Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.mondo.collaboration.policy.rules.RulesPackage#getAssetType()
 * @model
 * @generated
 */
public enum AssetType implements Enumerator
{
  /**
   * The '<em><b>Object Fact</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OBJECT_FACT_VALUE
   * @generated
   * @ordered
   */
  OBJECT_FACT(0, "ObjectFact", "ObjectFact"),

  /**
   * The '<em><b>Reference Fact</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REFERENCE_FACT_VALUE
   * @generated
   * @ordered
   */
  REFERENCE_FACT(1, "ReferenceFact", "ReferenceFact"),

  /**
   * The '<em><b>Attribute Fact</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ATTRIBUTE_FACT_VALUE
   * @generated
   * @ordered
   */
  ATTRIBUTE_FACT(2, "AttributeFact", "AttributeFact");

  /**
   * The '<em><b>Object Fact</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Object Fact</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OBJECT_FACT
   * @model name="ObjectFact"
   * @generated
   * @ordered
   */
  public static final int OBJECT_FACT_VALUE = 0;

  /**
   * The '<em><b>Reference Fact</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Reference Fact</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REFERENCE_FACT
   * @model name="ReferenceFact"
   * @generated
   * @ordered
   */
  public static final int REFERENCE_FACT_VALUE = 1;

  /**
   * The '<em><b>Attribute Fact</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Attribute Fact</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ATTRIBUTE_FACT
   * @model name="AttributeFact"
   * @generated
   * @ordered
   */
  public static final int ATTRIBUTE_FACT_VALUE = 2;

  /**
   * An array of all the '<em><b>Asset Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final AssetType[] VALUES_ARRAY =
    new AssetType[]
    {
      OBJECT_FACT,
      REFERENCE_FACT,
      ATTRIBUTE_FACT,
    };

  /**
   * A public read-only list of all the '<em><b>Asset Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<AssetType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Asset Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AssetType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AssetType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Asset Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AssetType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AssetType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Asset Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AssetType get(int value)
  {
    switch (value)
    {
      case OBJECT_FACT_VALUE: return OBJECT_FACT;
      case REFERENCE_FACT_VALUE: return REFERENCE_FACT;
      case ATTRIBUTE_FACT_VALUE: return ATTRIBUTE_FACT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private AssetType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //AssetType
