/**
 * generated by Xtext 2.10.0
 */
package org.mondo.collaboration.policy.rules;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Fact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mondo.collaboration.policy.rules.ReferenceFact#getSrcObject <em>Src Object</em>}</li>
 *   <li>{@link org.mondo.collaboration.policy.rules.ReferenceFact#getReference <em>Reference</em>}</li>
 *   <li>{@link org.mondo.collaboration.policy.rules.ReferenceFact#getTrgObject <em>Trg Object</em>}</li>
 * </ul>
 *
 * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact()
 * @model
 * @generated
 */
public interface ReferenceFact extends EObject
{
  /**
   * Returns the value of the '<em><b>Src Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Src Object</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src Object</em>' reference.
   * @see #setSrcObject(EObject)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact_SrcObject()
   * @model
   * @generated
   */
  EObject getSrcObject();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getSrcObject <em>Src Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src Object</em>' reference.
   * @see #getSrcObject()
   * @generated
   */
  void setSrcObject(EObject value);

  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(EReference)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact_Reference()
   * @model
   * @generated
   */
  EReference getReference();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(EReference value);

  /**
   * Returns the value of the '<em><b>Trg Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trg Object</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trg Object</em>' reference.
   * @see #setTrgObject(EObject)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact_TrgObject()
   * @model
   * @generated
   */
  EObject getTrgObject();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getTrgObject <em>Trg Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trg Object</em>' reference.
   * @see #getTrgObject()
   * @generated
   */
  void setTrgObject(EObject value);

} // ReferenceFact
