/**
 * generated by Xtext 2.10.0
 */
package org.mondo.collaboration.policy.rules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Fact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mondo.collaboration.policy.rules.ReferenceFact#getSourceParam <em>Source Param</em>}</li>
 *   <li>{@link org.mondo.collaboration.policy.rules.ReferenceFact#getTargetParam <em>Target Param</em>}</li>
 * </ul>
 *
 * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact()
 * @model
 * @generated
 */
public interface ReferenceFact extends Asset
{
  /**
   * Returns the value of the '<em><b>Source Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Param</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Param</em>' containment reference.
   * @see #setSourceParam(Parameter)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact_SourceParam()
   * @model containment="true"
   * @generated
   */
  Parameter getSourceParam();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getSourceParam <em>Source Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Param</em>' containment reference.
   * @see #getSourceParam()
   * @generated
   */
  void setSourceParam(Parameter value);

  /**
   * Returns the value of the '<em><b>Target Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Param</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Param</em>' containment reference.
   * @see #setTargetParam(Parameter)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getReferenceFact_TargetParam()
   * @model containment="true"
   * @generated
   */
  Parameter getTargetParam();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getTargetParam <em>Target Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Param</em>' containment reference.
   * @see #getTargetParam()
   * @generated
   */
  void setTargetParam(Parameter value);

} // ReferenceFact
