/**
 * generated by Xtext 2.10.0
 */
package org.mondo.collaboration.policy.rules;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.mondo.collaboration.policy.rules.RulesFactory
 * @model kind="package"
 * @generated
 */
public interface RulesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rules";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mondo.org/collaboration/policy/Rules";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rules";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RulesPackage eINSTANCE = org.mondo.collaboration.policy.rules.impl.RulesPackageImpl.init();

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.ModelImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ROLES = 0;

  /**
   * The feature id for the '<em><b>Policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__POLICY = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.PolicyImpl <em>Policy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.PolicyImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getPolicy()
   * @generated
   */
  int POLICY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__NAME = 0;

  /**
   * The feature id for the '<em><b>Access</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__ACCESS = 1;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__OPERATION = 2;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__RULES = 3;

  /**
   * The feature id for the '<em><b>Resolution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY__RESOLUTION = 4;

  /**
   * The number of structural features of the '<em>Policy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.RuleImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getRule()
   * @generated
   */
  int RULE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Access</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACCESS = 1;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__OPERATION = 2;

  /**
   * The feature id for the '<em><b>Roles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ROLES = 3;

  /**
   * The feature id for the '<em><b>Asset</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ASSET = 4;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__QUERY = 5;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__BINDINGS = 6;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__PRIORITY = 7;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.RoleImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getRole()
   * @generated
   */
  int ROLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.UserImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getUser()
   * @generated
   */
  int USER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__NAME = ROLE__NAME;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.GroupImpl <em>Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.GroupImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getGroup()
   * @generated
   */
  int GROUP = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__NAME = ROLE__NAME;

  /**
   * The feature id for the '<em><b>Users</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__USERS = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.AssetImpl <em>Asset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.AssetImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getAsset()
   * @generated
   */
  int ASSET = 6;

  /**
   * The number of structural features of the '<em>Asset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.ObjectFactImpl <em>Object Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.ObjectFactImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getObjectFact()
   * @generated
   */
  int OBJECT_FACT = 7;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FACT__PARAMETER = ASSET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FACT_FEATURE_COUNT = ASSET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.ReferenceFactImpl <em>Reference Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.ReferenceFactImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getReferenceFact()
   * @generated
   */
  int REFERENCE_FACT = 8;

  /**
   * The feature id for the '<em><b>Source Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FACT__SOURCE_PARAM = ASSET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FACT__TARGET_PARAM = ASSET_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Reference Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FACT_FEATURE_COUNT = ASSET_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.QueryImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 9;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__PATTERN = 0;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.BindingImpl <em>Binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.BindingImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getBinding()
   * @generated
   */
  int BINDING = 10;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__PARAMETER = 0;

  /**
   * The feature id for the '<em><b>Bind</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__BIND = 1;

  /**
   * The number of structural features of the '<em>Binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.ParameterImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 11;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.BindImpl <em>Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.BindImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getBind()
   * @generated
   */
  int BIND = 12;

  /**
   * The number of structural features of the '<em>Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.impl.ObjectBindImpl <em>Object Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.impl.ObjectBindImpl
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getObjectBind()
   * @generated
   */
  int OBJECT_BIND = 13;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_BIND__OBJECT = BIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_BIND_FEATURE_COUNT = BIND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.AccessibilityLevel <em>Accessibility Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.AccessibilityLevel
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getAccessibilityLevel()
   * @generated
   */
  int ACCESSIBILITY_LEVEL = 14;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.OperationType <em>Operation Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.OperationType
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getOperationType()
   * @generated
   */
  int OPERATION_TYPE = 15;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.policy.rules.ResolutionType <em>Resolution Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.policy.rules.ResolutionType
   * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getResolutionType()
   * @generated
   */
  int RESOLUTION_TYPE = 16;


  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.mondo.collaboration.policy.rules.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.policy.rules.Model#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.mondo.collaboration.policy.rules.Model#getRoles()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Roles();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.Model#getPolicy <em>Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Policy</em>'.
   * @see org.mondo.collaboration.policy.rules.Model#getPolicy()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Policy();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Policy <em>Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Policy</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy
   * @generated
   */
  EClass getPolicy();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Policy#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy#getName()
   * @see #getPolicy()
   * @generated
   */
  EAttribute getPolicy_Name();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Policy#getAccess <em>Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Access</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy#getAccess()
   * @see #getPolicy()
   * @generated
   */
  EAttribute getPolicy_Access();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Policy#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy#getOperation()
   * @see #getPolicy()
   * @generated
   */
  EAttribute getPolicy_Operation();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.policy.rules.Policy#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy#getRules()
   * @see #getPolicy()
   * @generated
   */
  EReference getPolicy_Rules();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Policy#getResolution <em>Resolution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Resolution</em>'.
   * @see org.mondo.collaboration.policy.rules.Policy#getResolution()
   * @see #getPolicy()
   * @generated
   */
  EAttribute getPolicy_Resolution();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Rule#getAccess <em>Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Access</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getAccess()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Access();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Rule#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getOperation()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Operation();

  /**
   * Returns the meta object for the reference list '{@link org.mondo.collaboration.policy.rules.Rule#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Roles</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getRoles()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Roles();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.Rule#getAsset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Asset</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getAsset()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Asset();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.Rule#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getQuery()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Query();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.policy.rules.Rule#getBindings <em>Bindings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bindings</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getBindings()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Bindings();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Rule#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see org.mondo.collaboration.policy.rules.Rule#getPriority()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Priority();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.mondo.collaboration.policy.rules.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.policy.rules.Role#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mondo.collaboration.policy.rules.Role#getName()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Name();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see org.mondo.collaboration.policy.rules.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Group <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group</em>'.
   * @see org.mondo.collaboration.policy.rules.Group
   * @generated
   */
  EClass getGroup();

  /**
   * Returns the meta object for the reference list '{@link org.mondo.collaboration.policy.rules.Group#getUsers <em>Users</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Users</em>'.
   * @see org.mondo.collaboration.policy.rules.Group#getUsers()
   * @see #getGroup()
   * @generated
   */
  EReference getGroup_Users();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Asset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset</em>'.
   * @see org.mondo.collaboration.policy.rules.Asset
   * @generated
   */
  EClass getAsset();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.ObjectFact <em>Object Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Fact</em>'.
   * @see org.mondo.collaboration.policy.rules.ObjectFact
   * @generated
   */
  EClass getObjectFact();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.ObjectFact#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see org.mondo.collaboration.policy.rules.ObjectFact#getParameter()
   * @see #getObjectFact()
   * @generated
   */
  EReference getObjectFact_Parameter();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.ReferenceFact <em>Reference Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Fact</em>'.
   * @see org.mondo.collaboration.policy.rules.ReferenceFact
   * @generated
   */
  EClass getReferenceFact();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getSourceParam <em>Source Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source Param</em>'.
   * @see org.mondo.collaboration.policy.rules.ReferenceFact#getSourceParam()
   * @see #getReferenceFact()
   * @generated
   */
  EReference getReferenceFact_SourceParam();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.ReferenceFact#getTargetParam <em>Target Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target Param</em>'.
   * @see org.mondo.collaboration.policy.rules.ReferenceFact#getTargetParam()
   * @see #getReferenceFact()
   * @generated
   */
  EReference getReferenceFact_TargetParam();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.mondo.collaboration.policy.rules.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.policy.rules.Query#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pattern</em>'.
   * @see org.mondo.collaboration.policy.rules.Query#getPattern()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Pattern();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Binding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binding</em>'.
   * @see org.mondo.collaboration.policy.rules.Binding
   * @generated
   */
  EClass getBinding();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.Binding#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see org.mondo.collaboration.policy.rules.Binding#getParameter()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_Parameter();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.policy.rules.Binding#getBind <em>Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bind</em>'.
   * @see org.mondo.collaboration.policy.rules.Binding#getBind()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_Bind();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.mondo.collaboration.policy.rules.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.policy.rules.Parameter#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see org.mondo.collaboration.policy.rules.Parameter#getVariable()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Variable();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.Bind <em>Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bind</em>'.
   * @see org.mondo.collaboration.policy.rules.Bind
   * @generated
   */
  EClass getBind();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.policy.rules.ObjectBind <em>Object Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Bind</em>'.
   * @see org.mondo.collaboration.policy.rules.ObjectBind
   * @generated
   */
  EClass getObjectBind();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.policy.rules.ObjectBind#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see org.mondo.collaboration.policy.rules.ObjectBind#getObject()
   * @see #getObjectBind()
   * @generated
   */
  EReference getObjectBind_Object();

  /**
   * Returns the meta object for enum '{@link org.mondo.collaboration.policy.rules.AccessibilityLevel <em>Accessibility Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Accessibility Level</em>'.
   * @see org.mondo.collaboration.policy.rules.AccessibilityLevel
   * @generated
   */
  EEnum getAccessibilityLevel();

  /**
   * Returns the meta object for enum '{@link org.mondo.collaboration.policy.rules.OperationType <em>Operation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation Type</em>'.
   * @see org.mondo.collaboration.policy.rules.OperationType
   * @generated
   */
  EEnum getOperationType();

  /**
   * Returns the meta object for enum '{@link org.mondo.collaboration.policy.rules.ResolutionType <em>Resolution Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Resolution Type</em>'.
   * @see org.mondo.collaboration.policy.rules.ResolutionType
   * @generated
   */
  EEnum getResolutionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RulesFactory getRulesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.ModelImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ROLES = eINSTANCE.getModel_Roles();

    /**
     * The meta object literal for the '<em><b>Policy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__POLICY = eINSTANCE.getModel_Policy();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.PolicyImpl <em>Policy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.PolicyImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getPolicy()
     * @generated
     */
    EClass POLICY = eINSTANCE.getPolicy();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICY__NAME = eINSTANCE.getPolicy_Name();

    /**
     * The meta object literal for the '<em><b>Access</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICY__ACCESS = eINSTANCE.getPolicy_Access();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICY__OPERATION = eINSTANCE.getPolicy_Operation();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLICY__RULES = eINSTANCE.getPolicy_Rules();

    /**
     * The meta object literal for the '<em><b>Resolution</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICY__RESOLUTION = eINSTANCE.getPolicy_Resolution();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.RuleImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Access</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ACCESS = eINSTANCE.getRule_Access();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__OPERATION = eINSTANCE.getRule_Operation();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ROLES = eINSTANCE.getRule_Roles();

    /**
     * The meta object literal for the '<em><b>Asset</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ASSET = eINSTANCE.getRule_Asset();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__QUERY = eINSTANCE.getRule_Query();

    /**
     * The meta object literal for the '<em><b>Bindings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__BINDINGS = eINSTANCE.getRule_Bindings();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__PRIORITY = eINSTANCE.getRule_Priority();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.RoleImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__NAME = eINSTANCE.getRole_Name();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.UserImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.GroupImpl <em>Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.GroupImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getGroup()
     * @generated
     */
    EClass GROUP = eINSTANCE.getGroup();

    /**
     * The meta object literal for the '<em><b>Users</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP__USERS = eINSTANCE.getGroup_Users();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.AssetImpl <em>Asset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.AssetImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getAsset()
     * @generated
     */
    EClass ASSET = eINSTANCE.getAsset();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.ObjectFactImpl <em>Object Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.ObjectFactImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getObjectFact()
     * @generated
     */
    EClass OBJECT_FACT = eINSTANCE.getObjectFact();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_FACT__PARAMETER = eINSTANCE.getObjectFact_Parameter();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.ReferenceFactImpl <em>Reference Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.ReferenceFactImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getReferenceFact()
     * @generated
     */
    EClass REFERENCE_FACT = eINSTANCE.getReferenceFact();

    /**
     * The meta object literal for the '<em><b>Source Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_FACT__SOURCE_PARAM = eINSTANCE.getReferenceFact_SourceParam();

    /**
     * The meta object literal for the '<em><b>Target Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_FACT__TARGET_PARAM = eINSTANCE.getReferenceFact_TargetParam();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.QueryImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__PATTERN = eINSTANCE.getQuery_Pattern();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.BindingImpl <em>Binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.BindingImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getBinding()
     * @generated
     */
    EClass BINDING = eINSTANCE.getBinding();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__PARAMETER = eINSTANCE.getBinding_Parameter();

    /**
     * The meta object literal for the '<em><b>Bind</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__BIND = eINSTANCE.getBinding_Bind();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.ParameterImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__VARIABLE = eINSTANCE.getParameter_Variable();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.BindImpl <em>Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.BindImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getBind()
     * @generated
     */
    EClass BIND = eINSTANCE.getBind();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.impl.ObjectBindImpl <em>Object Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.impl.ObjectBindImpl
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getObjectBind()
     * @generated
     */
    EClass OBJECT_BIND = eINSTANCE.getObjectBind();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_BIND__OBJECT = eINSTANCE.getObjectBind_Object();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.AccessibilityLevel <em>Accessibility Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.AccessibilityLevel
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getAccessibilityLevel()
     * @generated
     */
    EEnum ACCESSIBILITY_LEVEL = eINSTANCE.getAccessibilityLevel();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.OperationType <em>Operation Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.OperationType
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getOperationType()
     * @generated
     */
    EEnum OPERATION_TYPE = eINSTANCE.getOperationType();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.policy.rules.ResolutionType <em>Resolution Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.policy.rules.ResolutionType
     * @see org.mondo.collaboration.policy.rules.impl.RulesPackageImpl#getResolutionType()
     * @generated
     */
    EEnum RESOLUTION_TYPE = eINSTANCE.getResolutionType();

  }

} //RulesPackage
