/**
 * generated by Xtext 2.10.0
 */
package org.mondo.collaboration.policy.validation;

import org.mondo.collaboration.policy.validation.AbstractRulesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RulesValidator extends AbstractRulesValidator {
}
