/**
 * generated by Xtext 2.10.0
 */
package org.xtext.policy.rules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.policy.rules.Model#getPolicy <em>Policy</em>}</li>
 * </ul>
 *
 * @see org.xtext.policy.rules.RulesPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Policy</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Policy</em>' containment reference.
   * @see #setPolicy(Policy)
   * @see org.xtext.policy.rules.RulesPackage#getModel_Policy()
   * @model containment="true"
   * @generated
   */
  Policy getPolicy();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Model#getPolicy <em>Policy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Policy</em>' containment reference.
   * @see #getPolicy()
   * @generated
   */
  void setPolicy(Policy value);

} // Model
