/**
 * generated by Xtext 2.10.0
 */
package org.xtext.policy.rules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.policy.rules.Rule#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.policy.rules.Rule#getAccess <em>Access</em>}</li>
 *   <li>{@link org.xtext.policy.rules.Rule#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.policy.rules.Rule#getUser <em>User</em>}</li>
 *   <li>{@link org.xtext.policy.rules.Rule#getQuery <em>Query</em>}</li>
 *   <li>{@link org.xtext.policy.rules.Rule#getPriority <em>Priority</em>}</li>
 * </ul>
 *
 * @see org.xtext.policy.rules.RulesPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.policy.rules.RulesPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Access</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.policy.rules.AccessibilityLevel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Access</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access</em>' attribute.
   * @see org.xtext.policy.rules.AccessibilityLevel
   * @see #setAccess(AccessibilityLevel)
   * @see org.xtext.policy.rules.RulesPackage#getRule_Access()
   * @model
   * @generated
   */
  AccessibilityLevel getAccess();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getAccess <em>Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access</em>' attribute.
   * @see org.xtext.policy.rules.AccessibilityLevel
   * @see #getAccess()
   * @generated
   */
  void setAccess(AccessibilityLevel value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.policy.rules.OperationType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see org.xtext.policy.rules.OperationType
   * @see #setOperation(OperationType)
   * @see org.xtext.policy.rules.RulesPackage#getRule_Operation()
   * @model
   * @generated
   */
  OperationType getOperation();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see org.xtext.policy.rules.OperationType
   * @see #getOperation()
   * @generated
   */
  void setOperation(OperationType value);

  /**
   * Returns the value of the '<em><b>User</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>User</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>User</em>' containment reference.
   * @see #setUser(User)
   * @see org.xtext.policy.rules.RulesPackage#getRule_User()
   * @model containment="true"
   * @generated
   */
  User getUser();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getUser <em>User</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>User</em>' containment reference.
   * @see #getUser()
   * @generated
   */
  void setUser(User value);

  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference.
   * @see #setQuery(Query)
   * @see org.xtext.policy.rules.RulesPackage#getRule_Query()
   * @model containment="true"
   * @generated
   */
  Query getQuery();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getQuery <em>Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' containment reference.
   * @see #getQuery()
   * @generated
   */
  void setQuery(Query value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Priority</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see org.xtext.policy.rules.RulesPackage#getRule_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link org.xtext.policy.rules.Rule#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

} // Rule
