/*
 * generated by Xtext 2.10.0
 */
package org.xtext.policy.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRulesScopeProvider extends DelegatingScopeProvider {
}
